# Generated by Django 2.0 on 2019-05-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_type_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='content_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('action', models.CharField(max_length=225)),
                ('translate', models.TextField()),
                ('book_name', models.CharField(max_length=225)),
                ('length', models.IntegerField()),
                ('collection_nums', models.IntegerField()),
                ('delete_flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='crawler_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=225)),
                ('question', models.CharField(max_length=225)),
                ('length', models.IntegerField()),
                ('upvote', models.IntegerField()),
                ('collection_nums', models.IntegerField()),
                ('delete_flag', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.article_type_table')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('famale', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
