# Generated by Django 2.0 on 2019-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190514_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article_type_table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
