# Generated by Django 2.0 on 2019-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190517_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler_data',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
